apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-a
  labels:
    app: app-a
spec:
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - name: app-a
        image: salaboy/fmtok8s-java-cloudevents
        env:
        - name: SINK 
          value: http://application-b-service

---

apiVersion: v1
kind: Service
metadata:
  name: application-a-service
spec:
  selector:
    app: app-a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080